[workspace]

resolver = "3"

members = [
    "runtime/feo-runtime",

    "libraries/sdk/*",
    "libraries/core/*",
    "libraries/gfx/*",
    "libraries/hardware/*",
    "libraries/tools/*",
]

[workspace.dependencies]
feo-globals = { path = "libraries/sdk/feo-globals"}

feo-asset   = { path = "libraries/core/feo-asset" }
feo-file    = { path = "libraries/core/feo-file" }
feo-plug    = { path = "libraries/core/feo-plug" }

feo-color   = { path = "libraries/gfx/feo-color" }
feo-gui     = { path = "libraries/gfx/feo-gui" }
feo-render  = { path = "libraries/gfx/feo-render" }

feo-input   = { path = "libraries/hardware/feo-input" }
feo-memory  = { path = "libraries/hardware/feo-memory" }
feo-system  = { path = "libraries/hardware/feo-system" }
feo-clock    = { path = "libraries/hardware/feo-clock" }
feo-audio   = { path = "libraries/hardware/feo-audio" }
feo-physics = { path = "libraries/hardware/feo-physics" }

feo-debug   = { path = "libraries/tools/feo-debug" }
feo-math    = { path = "libraries/tools/feo-math" }

feo-sdk     = { path = "libraries/sdk/feo-sdk" }



[workspace.lints.rust]
dead_code = "allow"
unused = "allow"
