[package]
name = "feo-runtime"
version = "0.0.1"
authors = ["Sour"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
feo-globals.workspace = true

feo-debug.workspace = true
feo-memory.workspace = true
feo-math.workspace = true

feo-clock.workspace = true
feo-input.workspace = true
feo-audio.workspace = true
feo-asset.workspace = true
feo-file.workspace = true
feo-plug.workspace = true
feo-physics.workspace = true
feo-system.workspace = true

feo-color.workspace = true
feo-gui.workspace = true
feo-render.workspace = true

feo-sdk.workspace = true

[lints]
workspace = true